Uyuni 2024.03
uyuni-project/uyuni-project.github.io pull request #103
Opened 2024-04-15 07:35 UTC by raulillo82

Uyuni 2024.03

2024-04-15 08:53 UTC, juliogonzalez approved these changes

2024-04-15 09:52 UTC, deneb-alpha approved these changes
LGTM

2024-04-15 21:48 UTC, deneb-alpha requested changes
please update release date with the suggestions I made.
Please, also take the updated html for the release notes. 
the gitlab project with the release notes is updates and also OBS. but I can't pushed the refreshed html, you used a branch on your fork.

2024-04-15 21:48 UTC, deneb-alpha commented on index.html
> +              <span>15/04/2024</span>
```suggestion
              <span>16/04/2024</span>
```

2024-04-15 21:48 UTC, deneb-alpha commented on pages/news.html
> +            <p><strong>15/04/2024</strong> - Uyuni 2024.03 is now available with Confidential Computing Attestation, enhanced CVE Audit, Ansible security fixes and more! Check the <a href='../pages/s
```suggestion
            <p><strong>16/04/2024</strong> - Uyuni 2024.03 is now available with Confidential Computing Attestation, enhanced CVE Audit, Ansible security fixes and more! Check the <a href='../pages/stable-version.html#releasenotes'>release notes</a> for the full details!</p>
```

2024-04-16 09:35 UTC, deneb-alpha approved these changes
LGTM, but again,let's wait  for legal before merging

2024-04-16 10:14 UTC, juliogonzalez approved these changes

2024-04-16 10:15 UTC, juliogonzalez commented
Could be you need to change the PR a little according to what happens with the Uyuni Server as containers migrations/updates

2024-04-16 17:54 UTC, merged