Uyuni 2024.01
uyuni-project/uyuni-project.github.io pull request #90
Opened 2024-01-30 18:00 UTC by raulillo82

Please do not approve till I add the release notes files, as they haven't been merged yet and can still have changes.
But at least the rest can be reviewed.

2024-01-30 19:06 UTC, deneb-alpha requested changes
submitted a few  suggestions and comments

2024-01-30 19:06 UTC, deneb-alpha commented on index.html
> +              <p>Uyuni 2024.01 is now available! openEuler 22.03 is now supported as a client, reboot required indication for non-Suse distros, one-shot action execution to recurring custom state cre
```suggestion
              <p>Uyuni 2024.01 is now available! openEuler 22.03 is now supported as a client, reboot required indication for non-SUSE distros and much more! Check the <a href='pages/stable-version.html#releasenotes'>release notes</a> for the full details!</p>
```

2024-01-30 19:06 UTC, deneb-alpha commented on pages/devel-version.html
BTW, on 4.3.11 we  are not submitting Debian 10 that is  way after EOL. 

We  should remove  it  also from here I think. And  actually, it  could  make sense to mention the  EOL in the release notes too

2024-01-30 19:06 UTC, deneb-alpha commented on pages/stable-version.html
same as  for  the devel page...
on 4.3.11 we  are not submitting Debian 10 that is  way after EOL. 

We  should remove  it  also from here I think. And  actually, it  could  make sense to mention the  EOL in the release notes too

2024-01-30 19:06 UTC, deneb-alpha commented on pages/news.html
> +	  <p><strong>31/01/2024</strong> - Uyuni 2024.01 is now available! openEuler 22.03 is now supported as a client, reboot required indication for non-Suse distros, one-shot action execution to recurri
```suggestion
	  <p><strong>31/01/2024</strong> - Uyuni 2024.01 is now available! openEuler 22.03 is now supported as a client, reboot required indication for non-SUSE distros and much more! Check the <a href='../pages/stable-version.html#releasenotes'>release notes</a> for the full details!</p>
```

2024-01-30 22:07 UTC, raulillo82 commented on pages/devel-version.html
Fixed. OK for the release notes (that I still need to copy here).

2024-01-30 22:07 UTC, raulillo82 commented on pages/stable-version.html
Fixed. OK for the release notes (that I still need to copy here).

2024-01-30 22:11 UTC, raulillo82 commented on pages/devel-version.html
Actually no. When writing the release notes, I found out this:
https://wiki.debian.org/LTS -> June 2024. So still supported...
Let's confirm tomorrow, in that case I'll revert the last commit.

2024-01-30 22:12 UTC, raulillo82 commented on pages/stable-version.html
Actually no. When writing the release notes, I found out this:
https://wiki.debian.org/LTS -> June 2024. So still supported...
Let's confirm tomorrow, in that case I'll revert the last commit.

2024-01-31 08:40 UTC, raulillo82 commented on pages/stable-version.html
Clarified. It is not about LTS, but Security updates.

2024-01-31 08:41 UTC, raulillo82 commented on pages/devel-version.html
Clarified. It is not about LTS, but Security updates.

2024-01-31 12:38 UTC, deneb-alpha approved these changes
LGTM

2024-01-31 14:52 UTC, deneb-alpha approved these changes
LGTM

2024-01-31 14:56 UTC, deneb-alpha approved these changes
LGTM

2024-01-31 18:11 UTC, merged